/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soni.agencies;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.Iterator;
import java.util.Set;
import soni.agencies.data.ShopkeepersData;
import soni.agencies.db.BeatDetailsDb;
import soni.agencies.db.ShopkeeperDetailsDb;

/**
 *
 * @author YATRAONLINE\himanshu.soni
 */
public class ShopkeeperDetails extends javax.swing.JFrame {

    /**
     * Creates new form AddDetails
     */
    private Connection conn;
    private BeatDetails beatDetails;
    public ShopkeeperDetails() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        jLabelId.setVisible(false);
        jButtonUpdateDetails.setEnabled(false);
        jButtonDeleteDetails.setEnabled(false);
    }

    public ShopkeeperDetails(Connection conn){
        this();
        this.conn = conn;
        updateBeatDetails();
    }
    
    private ShopkeeperDetails(Connection conn, String beat) {
        this(conn);
        jComboBoxBeat.setSelectedItem(beat);
        jTextFieldName.grabFocus();
    }
    
    public ShopkeeperDetails(Connection conn, ShopkeepersData data, BeatDetails beatDetails){
        this(conn);
        this.beatDetails = beatDetails;
        jComboBoxBeat.setSelectedItem(data.getBeat());
        jTextFieldName.setText(data.getName());
        jTextFieldMobile.setText(data.getMobileNo());
        jTextFieldGst.setText(data.getGstNo());
        jTextFieldAdhaar.setText(data.getAdhaarNo());
        jTextFieldPan.setText(data.getPanNo());
        jTextFieldComposition.setText(data.getCompositionNo());
        jLabelId.setText(data.getId());
        jButtonUpdateDetails.setEnabled(true);
        jButtonDeleteDetails.setEnabled(true);
        jButtonAddDetails.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBeat = new javax.swing.JLabel();
        jComboBoxBeat = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelMobile = new javax.swing.JLabel();
        jTextFieldMobile = new javax.swing.JTextField();
        jLabelGst = new javax.swing.JLabel();
        jTextFieldGst = new javax.swing.JTextField();
        jLabelAdhaar = new javax.swing.JLabel();
        jTextFieldAdhaar = new javax.swing.JTextField();
        jLabelPan = new javax.swing.JLabel();
        jTextFieldPan = new javax.swing.JTextField();
        jLabelComposition = new javax.swing.JLabel();
        jTextFieldComposition = new javax.swing.JTextField();
        jButtonAddDetails = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jButtonUpdateDetails = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jButtonDeleteDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Shopkeeper Details");

        jLabelBeat.setText("Beat");

        jComboBoxBeat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Beat" }));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel2.setText("Shopkeeper Details");

        jLabelName.setText("Name");

        jLabelMobile.setText("Mobile No.");

        jLabelGst.setText("GST No.");

        jLabelAdhaar.setText("Adhaar No.");

        jLabelPan.setText("PAN No.");

        jLabelComposition.setText("Composition No.");

        jTextFieldComposition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCompositionFocusGained(evt);
            }
        });

        jButtonAddDetails.setText("Add Details");
        jButtonAddDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDetailsActionPerformed(evt);
            }
        });

        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonUpdateDetails.setText("Update Details");
        jButtonUpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateDetailsActionPerformed(evt);
            }
        });

        jButtonDeleteDetails.setText("Delete Details");
        jButtonDeleteDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMobile)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelBeat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelGst, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelComposition)
                            .addComponent(jLabelAdhaar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldGst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jTextFieldAdhaar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jTextFieldPan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jTextFieldComposition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jComboBoxBeat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldName)
                            .addComponent(jTextFieldMobile))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAddDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonUpdateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDeleteDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(38, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBeat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxBeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGst, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldGst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAdhaar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAdhaar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelComposition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldComposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelId)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddDetails)
                    .addComponent(jButtonUpdateDetails)
                    .addComponent(jButtonDeleteDetails))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDetailsActionPerformed
        boolean validate = validateDetails();
        if(validate){
            ShopkeeperDetailsDb detailsDb = new ShopkeeperDetailsDb();
            String beat = (String) jComboBoxBeat.getSelectedItem();
            String name = jTextFieldName.getText();
            String mobile_no = jTextFieldMobile.getText();
            String gst_no = jTextFieldGst.getText();
            String adhaar_no = jTextFieldAdhaar.getText();
            String pan_no = jTextFieldPan.getText();
            String composition_no = jTextFieldComposition.getText();
            boolean result = detailsDb.saveData(this.conn, beat, name, mobile_no, gst_no, adhaar_no, pan_no, composition_no);
            if(result){
                new ShopkeeperDetails(conn, beat).setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButtonAddDetailsActionPerformed

    private void jButtonUpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateDetailsActionPerformed
        boolean validate = validateDetails();
        if(validate){
            ShopkeeperDetailsDb detailsDb = new ShopkeeperDetailsDb();
            String beat = (String) jComboBoxBeat.getSelectedItem();
            String name = jTextFieldName.getText();
            String mobile_no = jTextFieldMobile.getText();
            String gst_no = jTextFieldGst.getText();
            String adhaar_no = jTextFieldAdhaar.getText();
            String pan_no = jTextFieldPan.getText();
            String composition_no = jTextFieldComposition.getText();
            String id = jLabelId.getText();
            boolean result = detailsDb.updateData(this.conn, id, beat, name, mobile_no, gst_no, adhaar_no, pan_no, composition_no);
            if(result){
                if(beatDetails != null)
                    beatDetails.updateShopkeeperDetails();
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButtonUpdateDetailsActionPerformed

    private void jButtonDeleteDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteDetailsActionPerformed
        String id = jLabelId.getText();
        boolean result = new ShopkeeperDetailsDb().deleteData(conn, id);
        if(result){
            if(beatDetails != null)
                    beatDetails.updateShopkeeperDetails();
            this.dispose();
        }
    }//GEN-LAST:event_jButtonDeleteDetailsActionPerformed

    private void jTextFieldCompositionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCompositionFocusGained
        if(jButtonAddDetails.isEnabled())
            this.getRootPane().setDefaultButton(jButtonAddDetails);
        else
            this.getRootPane().setDefaultButton(jButtonUpdateDetails);
    }//GEN-LAST:event_jTextFieldCompositionFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopkeeperDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopkeeperDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopkeeperDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopkeeperDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopkeeperDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDetails;
    private javax.swing.JButton jButtonDeleteDetails;
    private javax.swing.JButton jButtonUpdateDetails;
    private javax.swing.JComboBox<String> jComboBoxBeat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAdhaar;
    private javax.swing.JLabel jLabelBeat;
    private javax.swing.JLabel jLabelComposition;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelGst;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMobile;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPan;
    private javax.swing.JTextField jTextFieldAdhaar;
    private javax.swing.JTextField jTextFieldComposition;
    private javax.swing.JTextField jTextFieldGst;
    private javax.swing.JTextField jTextFieldMobile;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPan;
    // End of variables declaration//GEN-END:variables

    private boolean validateDetails() {
        String mobileRegex = "^[0-9]{10}$";
        String panRegex = "(?i)^[a-z]{3}[cphfatblj][a-z][0-9]{4}[a-z]$";
        String adhaarRegex = "";
        String gstRegex = "";
        String compositionRegex = "";
        String nameRegex = "";
        
        String beat = jComboBoxBeat.getSelectedItem().toString();
        String name = jTextFieldName.getText();
        String mobile = jTextFieldMobile.getText();
        String gst = jTextFieldGst.getText();
        String adhaar = jTextFieldAdhaar.getText();
        String pan = jTextFieldPan.getText();
        String composition = jTextFieldComposition.getText();
        
        if(beat.equalsIgnoreCase("Select Beat")){
            jLabelError.setText("Please select a beat name");
            return false;
        }
        if(name.isEmpty()){
            jLabelError.setText("Please enter name of shopkeeper");
            return false;
        }
        if(!mobile.isEmpty() && !mobile.matches(mobileRegex)){
            jLabelError.setText("Please enter valid 10 digit mobile no.");
            return false;
        }
        if(!pan.isEmpty() && !pan.matches(panRegex)){
            jLabelError.setText("Please enter valid pan no.");
            return false;
        }
        jLabelError.setText("");
        return true;
    }

    private void updateBeatDetails() {
        BeatDetailsDb details = new BeatDetailsDb();
        Set<String> beats = details.getBeats(conn);
        Iterator<String> itr = beats.iterator();
        while(itr.hasNext()){
            jComboBoxBeat.addItem(itr.next());
        }
    }
}
